#import <Cocoa/Cocoa.h>
#import "TBCompat.h"

@class RelayRequest;
@class TBStore;

@interface ChatController : NSObject {
    NSWindow *window;
    NSPopUpButton *workspacePopup;
    NSView *content;
    NSTableView *table;
    NSScrollView *chatScroll;
    NSScrollView *transcriptScroll;
    NSButton *newButton;
    NSButton *deleteButton;
    NSPopUpButton *toolsPopup;
    NSButton *stopButton;
    NSButton *editButton;
    NSButton *retryButton;
    NSButton *attachButton;
    NSMutableArray *attachQueue;
    NSTextView *fieldEditor;
    id finder;
    double lastPartialSave;
    NSMutableArray *attachProblems;
    BOOL attachWorking;
    NSString *relayVersion;
    NSTextField *thinkingField;
    NSString *runId;
    NSMutableDictionary *workspaceSettings;
    NSArray *toolCatalog;
    NSString *commanderProblem;
    NSString *commanderCode;
    NSString *thinkingText;
    NSMutableArray *queuedGuidance;
    NSArray *editBackup;
    NSString *editedText;
    double lastFrame;
    double lastPaintRequest;
    BOOL stopping;
    BOOL paintScheduled;
    BOOL offeredSSH;
    int pulse;
    NSTimer *pulseTimer;
    RelayRequest *sideRequest;
    NSDictionary *commanderCache;
    BOOL commanderStatusPending;
    NSPopUpButton *modelPopup;
    NSPopUpButton *variantPopup;
    NSButton *sendButton;
    NSTextField *input;
    NSTextField *renameField;
    int renameRow;
    id transcript;
    NSMutableArray *chats;
    NSMutableDictionary *current;
    TBStore *store;
    NSString *workspaceChoice;
    int streamDepth;
    int streamEndDeferred;
    BOOL compactForced;
    BOOL compactOnly;
    BOOL layingOut;
    BOOL suppressSelection;
    BOOL busy;
    void *bodyStream;
    double lastPaint;
    NSMutableData *frameBuffer;
    NSMutableData *errorBody;
    int httpStatus;
    NSString *streamingId;
    NSString *launchQuestion;
    NSTextField *contextField;
    NSSplitView *split;
    NSView *sidePane;
    NSView *chatPane;
    float sidebarWidth;
    float inputHeight;
    BOOL naming;
    NSMutableArray *localModels;
    NSMutableDictionary *prefsFields;
    NSWindow *prefsWindow;
    NSMutableDictionary *contextPending;
    NSTextField *relayStatusField;
    NSTimer *relayTimer;
    BOOL relayReachable;
    double lastCatalog;
}

- (void)setLaunchQuestion:(NSString *)text;
- (void)layoutSubviews;

@end
